### ISSUE TITLE
想请教下目录格式的设置

### ISSUE THREAD

**Issue by MattixLee** [shuosc/SHU-Bachelor-Thesis-OSC#1]
您好，

        我现在使用其他的latex模板时遇到一个目录格式的问题，在目录中，一级标题，中英文摘要与对应的页码间没有指引线（连接用的小圆点），请问这个应该怎么设置下解决这个问题？

谢谢您！
祝好！

**Comment by EnJiang** [comment]
https://www.zhihu.com/question/41960738

**Comment by MattixLee** [comment]
谢谢您！
