### ISSUE TITLE
仍有多处格式与学校要求不同

### ISSUE THREAD

**Issue by kaleidoscope257-git** [shuosc/SHU-Bachelor-Thesis-OSC#14]
包括但不限于：
- 学校要求的**章节**格式为 \arabic{chapter}+章节+\chinese{chapter}
- 学校要求的**目录**中并不包含**摘要**
- 学校要求的**摘要** 中并不包含**论文题目**

希望能够得到维护者关注并得到解决，不胜感激！

**Comment by DavidXu-JJ** [comment]
I solve your issue in my pull request which mentions this issue above. If you don't have other questions, you can close this issue.

**Comment by littlePING-221** [comment]
对于第一条章节格式问题，我认为学校模板给出的“1 章节一”中的“章节一”是自己章节名的意思，例如“1 绪论”，而非“1 章节一 绪论”
![2023-05-15_22-54](https://github.com/shuosc/SHU-Bachelor-Thesis-OSC/assets/26323716/467eeacf-b780-43b5-be62-93fe4a94001e)
但是学校模板也是自相矛盾的，在目录中给出的格式是`\chinese{chapter}、`即“一、绪论”，在文字说明中也是这个意思
![2023-05-15_22-58](https://github.com/shuosc/SHU-Bachelor-Thesis-OSC/assets/26323716/cfd3ac30-9707-4ad2-8590-40f382135952)

**Comment by DavidXu-JJ** [comment]
For your first question, please compile the current version in your local device. At least my local version doesn't have such a problem.
For your second question, I have already tried your suggestion for hours before I create the pull request and I don't want to explain why your suggestion won't work in my opinion. If you think you can write a better version, you should open a pull request and try to fix my code.

**Comment by DavidXu-JJ** [comment]
Or maybe you can try to define the \mychapter in .dtx file. I haven't give it a try yet.

**Comment by kaleidoscope257-git** [comment]
> 对于第一条章节格式问题，我认为学校模板给出的“1 章节一”中的“章节一”是自己章节名的意思，例如“1 绪论”，而非“1 章节一 绪论” ![2023-05-15_22-54](https://user-images.githubusercontent.com/26323716/238387525-467eeacf-b780-43b5-be62-93fe4a94001e.png) 但是学校模板也是自相矛盾的，在目录中给出的格式是`\chinese{chapter}、`即“一、绪论”，在文字说明中也是这个意思 ![2023-05-15_22-58](https://user-images.githubusercontent.com/26323716/238388847-cfd3ac30-9707-4ad2-8590-40f382135952.png)

嗯嗯，是我当时没仔细看，你说的对。除此之外还有一个比较关键的一点是，论文要求的摘要是在toc之前的，这一点还望注意下
