### ISSUE TITLE
在调用listing环境插入代码块时遇到报错

### ISSUE THREAD

**Issue by Kai2510** [shuosc/SHU-Bachelor-Thesis-OSC#29]
RT，想在附录里插入代码，并以Python样式语法高亮。在.dtx文件里面发现了LaTeX的引用格式设置，但是在论文正文的tex文件里调用`\lstinputlisting` 或者`\begin{listings}`均提示`Undefined control sequence`。尝试在main.tex里面加`\usepackage{listings}`，报错变成了`Package Listings Error: Couldn't load requested style.`
想请教一下，如何修改，才能插入代码。

**Comment by LuminolT** [comment]
可以尝试在 `\usepackage{listings}` 后重新定义列表样式

**Comment by Kai2510** [comment]
> 可以尝试在 `\usepackage{listings}` 后重新定义列表样式

感谢。问题已解决。也许我之后可以尝试写到dtx里面去？

**Comment by jamesnulliu** [comment]
这个问题已经在 #34 解决
