### ISSUE TITLE
公式与正文的间距过大

### ISSUE THREAD

**Issue by Kai2510** [shuosc/SHU-Bachelor-Thesis-OSC#31]
RT，所有的公式前的行间距都过大。

![图片](https://github.com/shuosc/SHU-Bachelor-Thesis-OSC/assets/36656899/2f400327-4144-4c42-a1c1-2ec184a219be)

**Comment by YANthinkn** [comment]
文字结束和公式的\begin之前不换行试试看？

**Comment by Kai2510** [comment]
> 文字结束和公式的\begin之前不换行试试看？

感谢，已解决。
