### ISSUE TITLE
在macOS和Linux下编译的标题字体不对

### ISSUE THREAD

**Issue by AdrianDuan** [shuosc/SHU-Bachelor-Thesis-OSC#5]
![2F1510283A9340A9E16444A74671B50D](https://user-images.githubusercontent.com/26034046/82295387-46efca00-99e2-11ea-98cf-7c19b05a5c8a.jpg)

在macOS和Linux环境下，编译出来的标题字体为衬线字体，实际要求应该为黑体

**Comment by AdrianDuan** [comment]
@2014CAIS01 蔡主席帮忙提个PR吧

**Comment by 2014CAIS01** [comment]
我也在 overleaf (linux) 上 遇到了同样的问题，目测是 `\bfseries` 的原因。

有个dirty hack 是此处的 `\bfseries` 改成 `\heiti`。
https://github.com/shuosc/SHU-Bachelor-Thesis-OSC/blob/7c4ead2d01e677c7a1d97fdbf0f04709ded4532d/main.tex#L13-L18

`abstract.tex` 也做类似处理。

**Comment by 2014CAIS01** [comment]
调查发现是ctex中在不同系统下的 fontset 定义不同。这里提供两种解决方式：

1. 在 `main.tex` 导言区添加以下代码：

```tex
\setCJKmainfont{FandolSong-Regular}[BoldFont=FandolHei-Regular,ItalicFont = FandolKai-Regular] 
```

Mac  用户也可以使用（未测试，建议 @AdrianDuan 测试一下）
```tex
\setCJKmainfont{Songti~SC~Light}[BoldFont=Heiti~SC~Light,ItalicFont=Kaiti~SC, BoldItalicFont=Kaiti~SC~Bold] 
```

2. 将代码
https://github.com/shuosc/SHU-Bachelor-Thesis-OSC/blob/22e1021edd1abe1ac46df1e2bcbddea02a90f28a/shuthesis.cls#L59

添加 `fontset=windows` ，即修改为：
```tex
\LoadClass[a4paper,UTF8,zihao=-4,scheme=plain,fontset=windows]{ctexbook}
```

需要安装有 Windows 字体 。
