### ISSUE TITLE
关于引用格式

### ISSUE THREAD

**Issue by DMax1314** [shuosc/SHU-Bachelor-Thesis-OSC#7]
目前的引用格式严格来说并不符合GB/T7714-2015的标准，具体标准参考格式可以参照
https://gs.fudan.edu.cn/_upload/article/files/e2/3e/0197d0d64cbea9d9fae9a668329f/b9a3a4c2-1e6f-4e81-9974-36eb01635471.pdf
是否考虑采用https://github.com/hushidong/biblatex-gb7714-2015 的格式
修改时直接修改bibstyle即可：\bibliographystyle{gbt7714-numerical}

**Comment by DavidXu-JJ** [comment]
https://github.com/shuosc/SHU-Bachelor-Thesis-OSC/pull/9#issue-1699798490
